debug: true

server:
  port: 8000
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth?autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: 2580467z